version: "3.4"
services:
  projet-graph:
    container_name: projet-graph
    build:
        context: .
        target: dev
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app